# Generated by Django 5.1.1 on 2024-09-24 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rangoapp', '0003_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
