# Generated by Django 5.1.1 on 2024-09-24 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rangoapp', '0005_chatroom_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
