# Generated by Django 5.1.1 on 2024-09-24 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rangoapp', '0007_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
