# Generated by Django 5.1.1 on 2024-09-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rangoapp', '0010_userprofile_facebook_url_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
