# Generated by Django 5.1.1 on 2024-09-26 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rangoapp', '0011_userprofile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
